# Generated by Django 4.0.1 on 2022-01-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedInUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth', models.BooleanField()),
                ('email_address', models.EmailField(max_length=254)),
                ('hashed', models.CharField(max_length=350)),
            ],
        ),
    ]
